# fly.toml file generated for chatgpt-bot on 2022-12-09T14:17:33+08:00

app = "chatgpt-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DATA_FOLDER = "/data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[mounts]]
source="data"
destination="/data"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
